# Generated by Django 4.0.3 on 2022-03-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dietplan_equipments_workoutplan_reccommendeddiet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='full_name',
        ),
    ]
