# Generated by Django 4.0.3 on 2022-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_clientuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
