# Generated by Django 3.2.8 on 2022-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_clientuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='equipment_Desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
