# Generated by Django 3.2.8 on 2022-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_equipments_equipment_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='equipment_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
